### ISSUE TITLE
undefined method `postmark_settings='

### ISSUE THREAD

**Issue by oyeanuj** [scienceexchange/postmark_mailer#4]
Hi folks, thank you for open sourcing this! As I was giving it a run, I kept getting the following errors (even though I believe I followed all the README instructions).

I am using Rails 5 (with 'DEV-4132' branch).

```rb
Exiting
/Users/anuj/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/actionmailer-5.1.5/lib/action_mailer/base.rb:580:in `method_missing': undefined method `postmark_settings=' for ActionMailer::Base:Class (NoMethodError)
Did you mean?  smtp_settings=
	from /Users/anuj/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/actionmailer-5.1.5/lib/action_mailer/railtie.rb:47:in `block (3 levels) in <class:Railtie>'
```

Any ideas on what might be going on?

**Comment by oyeanuj** [comment]
@SeriouslyAwesome @miloshadzic Just following up, any ideas or thoughts on this one? 

Thank you!

**Comment by oyeanuj** [comment]
Figured out my own mistake, got confused with the instructions from the two packages.

Thanks @temochka for the help!

**Comment by miloshadzic** [comment]
@oyeanuj Glad you figured it out. I somehow didn't see your previous emails.
