### ISSUE TITLE
Release a gem on rubygems?

### ISSUE THREAD

**Issue by brendon** [scienceexchange/postmark_mailer#6]
Would it be possible to publish this gem on rubygems? :)

**Comment by flybayer** [comment]
Yes please :)

**Comment by SeriouslyAwesome** [comment]
Hey @brendon and @flybayer sorry for the delay. I've just published this on [Rubygems.org](https://rubygems.org/gems/postmark_mailer)! Glad you guys are finding this useful! I'll close this issue out now and update the documentation shortly.
